version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express_app
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    command: ["npm", "start"] 

  db:
    image: mysql:8.0
    container_name: express_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webservices
      MYSQL_USER: webuser
      MYSQL_PASSWORD: webpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
